# 使用するベースイメージを指定します。Node.js の LTS バージョンを使用します。
FROM node:16-alpine

# コンテナ内でアプリケーションファイルを保持するディレクトリを指定します。
WORKDIR /app

# アプリケーションの依存ファイルをコピー
COPY package*.json ./

# 依存関係をインストール
RUN npm install

# アプリケーションのソースをコピー
COPY . .

# アプリケーションがリッスンするポートを指定
EXPOSE 3000

# アプリケーションを起動
CMD ["npm", "start"]